---
abstract: 'Basic HTTP Auth Helper'
author:
  - 'Glen Hinkle'
build_requires:
  Mojo::IOLoop: 0
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-BasicAuth
recommends: {}
requires:
  Mojo::ByteStream: 0
  Mojolicious::Plugin: 0
version: 0.02
